import json
import re
from .gemini_service import call_gemini

def analyze_writing_dna(text):
    """
    VeriMind v5.0 | Writing DNA Analyzer
    Detects tone, complexity, readability, AI probability, and bias.
    """
    system_prompt = """
    You are the VeriMind Writing DNA Analyzer. 
    Perform a deep linguistic and stylistic audit of the provided text.

    METRICS TO EVALUATE:
    1. Tone: (Professional, Casual, Aggressive, Empathetic, etc.)
    2. Complexity: Linguistic depth (0-100).
    3. Readability: (Grade Level or Difficulty).
    4. AI Probability: Likelihood the text was generated by an LLM (0-100).
    5. Bias Indicator: Detect political, social, or cognitive biases (Low, Medium, High).

    OUTPUT SCHEMA (JSON):
    {
      "overall_dna": "Brief description of the writing style.",
      "metrics": {
        "tone": "string",
        "complexity_score": number (0-100),
        "readability_level": "string",
        "ai_probability": number (0-100),
        "bias_index": "Low" | "Medium" | "High"
      },
      "stylistic_traits": ["Trait 1", "Trait 2"],
      "visual_data": {
        "lexical_richness": number,
        "sentence_variation": number,
        "robotic_markers": number
      }
    }
    """

    try:
        response = call_gemini(text, system_instruction=system_prompt)
        match = re.search(r'\{.*\}', response, re.DOTALL)
        if match:
            return json.loads(match.group(0))
        else:
            raise ValueError("No JSON found")
    except Exception:
        return {
            "overall_dna": "Analysis Unavailable",
            "metrics": {
                "tone": "Neutral",
                "complexity_score": 0,
                "readability_level": "Unknown",
                "ai_probability": 0,
                "bias_index": "Low"
            },
            "stylistic_traits": [],
            "visual_data": {"lexical_richness": 0, "sentence_variation": 0, "robotic_markers": 0}
        }
