import os
import json
import re
import logging
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from .gemini_service import call_gemini

logger = logging.getLogger(__name__)

def generate_ppt_plan(topic):
    """
    Step 1: Use Gemini to generate a slide-by-slide structure.
    """
    prompt = f"""
    Create a detailed PowerPoint presentation outline for the topic: "{topic}".
    Provide a title for each slide and detailed bullet points for the content.
    
    Output STRICTLY as a JSON array of objects:
    [
      {{ "title": "Slide Title", "content": ["Point 1", "Point 2", "Point 3"] }},
      ...
    ]
    Include 5-7 slides.
    """
    try:
        response = call_gemini(prompt)
        match = re.search(r'\[.*\]', response, re.DOTALL)
        if match:
            return json.loads(match.group(0))
        return []
    except Exception as e:
        logger.error(f"PPT Plan Error: {e}")
        return []

def create_ppt_file(slides_data, filename="presentation.pptx"):
    """
    Step 2: Create the actual .pptx file using python-pptx.
    """
    try:
        prs = Presentation()
        
        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = slides_data[0]['title'] if slides_data else "Untitled Presentation"
        subtitle.text = "Generated by Verimind AI Neural Suite"

        # Content Slides
        for slide_data in slides_data[1:]:
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            
            title_shape = slide.shapes.title
            title_shape.text = slide_data['title']
            
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.text = slide_data['content'][0] if slide_data['content'] else ""
            
            for point in slide_data['content'][1:]:
                p = tf.add_paragraph()
                p.text = point
                p.level = 0

        # Save to a temporary location or a specific static folder
        output_path = os.path.join("server", "static", "exports", filename)
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        prs.save(output_path)
        return f"/static/exports/{filename}"
    except Exception as e:
        logger.error(f"PPT File Creation Error: {e}")
        return None
